### ISSUE TITLE
Add TDP to config

### ISSUE THREAD

**Issue by ohuu** [Root-Branch/cardamon#29]
We need a way to specify the TDP of the processor that cardamon is running on.

```toml
debug_level = "info"                                    # Optional - defaults to "info"
metrics_server_url = "http://cardamon.rootandbranch.io" # Optional - assumes local db if not specifed
tdp = 24      # <---- TDP in watts 
```
