### ISSUE TITLE
Handle process stdout and stderr

### ISSUE THREAD

**Issue by ohuu** [Root-Branch/cardamon#40]
All processes run by Cardamon have their stdout swallowed. We should add settings to the config file for configuring how each processes has stdout and stderr handled.

By default it will be swallowed, you could specify a file to direct the output to or have it displayed to Cardamon's stdout and stderr.

e.g.
```toml
[[processes]]

stdout = 'ignore' | 'attached' | '<path>'
stderr = 'ignore' | 'attached' | '<path>'
```
