### ISSUE TITLE
Allow scenarios to be a customizable command 

### ISSUE THREAD

**Issue by seal** [Root-Branch/cardamon#8]
Feature request:

I want to allow scenarios to be the users own command, rather than prefixed to be node.

Scenarios run via a card.conf file 

e.g. ( pseudo-code ) 
```toml
[scenario]
commands = ["node src/index.js"  , "node {filePath}"]
```
where {filePath} will be interchangeable
